// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using turnfix.Models;

#nullable disable

namespace turnfix.Migrations
{
    [DbContext(typeof(TurnfixContext))]
    partial class TurnfixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("turnfix.Models.TfxBereiche", b =>
                {
                    b.Property<int>("IntBereicheid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_bereicheid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntBereicheid"));

                    b.Property<bool?>("BolMaennlich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_maennlich");

                    b.Property<bool?>("BolWeiblich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_weiblich");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntBereicheid")
                        .HasName("pkx_bereicheid");

                    b.ToTable("tfx_bereiche", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxDisgrpXDisziplinen", b =>
                {
                    b.Property<int>("IntDisgrpXDisziplinenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_disgrp_x_disziplinenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntDisgrpXDisziplinenid"));

                    b.Property<int>("IntDisziplinenGruppenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinen_gruppenid");

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntPos")
                        .HasColumnType("smallint")
                        .HasColumnName("int_pos");

                    b.HasKey("IntDisgrpXDisziplinenid")
                        .HasName("pky_disgrp_x_disziplinen");

                    b.HasIndex("IntDisziplinenGruppenid");

                    b.HasIndex("IntDisziplinenid");

                    b.ToTable("tfx_disgrp_x_disziplinen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.Discipline", b =>
                {
                    b.Property<int>("IntDisziplinenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntDisziplinenid"));

                    b.Property<bool?>("BolBahnen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_bahnen");

                    b.Property<bool?>("BolBerechnen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_berechnen");

                    b.Property<bool?>("BolM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_m");

                    b.Property<bool?>("BolW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_w");

                    b.Property<short?>("IntBerechnung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("int_berechnung");

                    b.Property<int?>("IntFormelid")
                        .HasColumnType("integer")
                        .HasColumnName("int_formelid");

                    b.Property<int>("IntSportid")
                        .HasColumnType("integer")
                        .HasColumnName("int_sportid");

                    b.Property<int?>("IntVersuche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("int_versuche");

                    b.Property<string>("VarEinheit")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_einheit");

                    b.Property<string>("VarFormel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("var_formel");

                    b.Property<string>("VarIcon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("var_icon");

                    b.Property<string>("VarKuerzel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("var_kuerzel");

                    b.Property<string>("VarKurz1")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("var_kurz1");

                    b.Property<string>("VarKurz2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("var_kurz2");

                    b.Property<string>("VarMaske")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("var_maske");

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntDisziplinenid")
                        .HasName("pky_disziplinenid");

                    b.HasIndex("IntFormelid");

                    b.HasIndex("IntSportid");

                    b.ToTable("tfx_disziplinen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxDisziplinenFelder", b =>
                {
                    b.Property<int>("IntDisziplinenFelderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinen_felderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntDisziplinenFelderid"));

                    b.Property<bool?>("BolAusgangswert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_ausgangswert");

                    b.Property<bool?>("BolEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_enabled");

                    b.Property<bool?>("BolEndwert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_endwert");

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntGruppe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_gruppe");

                    b.Property<short?>("IntSortierung")
                        .HasColumnType("smallint")
                        .HasColumnName("int_sortierung");

                    b.Property<string>("VarName")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("var_name");

                    b.HasKey("IntDisziplinenFelderid")
                        .HasName("pky_disziplinen_felderid");

                    b.HasIndex("IntDisziplinenid");

                    b.ToTable("tfx_disziplinen_felder", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxDisziplinenGruppen", b =>
                {
                    b.Property<int>("IntDisziplinenGruppenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinen_gruppenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntDisziplinenGruppenid"));

                    b.Property<string>("TxtComment")
                        .HasColumnType("text")
                        .HasColumnName("txt_comment");

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntDisziplinenGruppenid")
                        .HasName("pky_disziplinen_gruppenid");

                    b.ToTable("tfx_disziplinen_gruppen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxFormeln", b =>
                {
                    b.Property<int>("IntFormelid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_formelid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntFormelid"));

                    b.Property<short?>("IntTyp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_typ");

                    b.Property<string>("VarFormel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_formel");

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntFormelid")
                        .HasName("pky_formeln");

                    b.ToTable("tfx_formeln", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxGaue", b =>
                {
                    b.Property<int>("IntGaueid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_gaueid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntGaueid"));

                    b.Property<int>("IntVerbaendeid")
                        .HasColumnType("integer")
                        .HasColumnName("int_verbaendeid");

                    b.Property<string>("VarKuerzel")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("var_kuerzel");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntGaueid")
                        .HasName("pky_gaueid");

                    b.HasIndex("IntVerbaendeid");

                    b.ToTable("tfx_gaue", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxGruppen", b =>
                {
                    b.Property<int>("IntGruppenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_gruppenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntGruppenid"));

                    b.Property<int>("IntVereineid")
                        .HasColumnType("integer")
                        .HasColumnName("int_vereineid");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntGruppenid")
                        .HasName("pky_gruppenid");

                    b.ToTable("tfx_gruppen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxGruppenXTeilnehmer", b =>
                {
                    b.Property<int>("IntGruppenXTeilnehmerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_gruppen_x_teilnehmerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntGruppenXTeilnehmerid"));

                    b.Property<int>("IntGruppenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_gruppenid");

                    b.Property<int>("IntTeilnehmerid")
                        .HasColumnType("integer")
                        .HasColumnName("int_teilnehmerid");

                    b.HasKey("IntGruppenXTeilnehmerid")
                        .HasName("pky_gruppen_x_teilnehmerid");

                    b.HasIndex("IntGruppenid");

                    b.HasIndex("IntTeilnehmerid");

                    b.ToTable("tfx_gruppen_x_teilnehmer", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxJuryResult", b =>
                {
                    b.Property<int>("IntJuryresultsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_juryresultsid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntJuryresultsid"));

                    b.Property<int?>("IntDisziplinenFelderid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinen_felderid");

                    b.Property<short?>("IntKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_kp");

                    b.Property<short?>("IntVersuch")
                        .HasColumnType("smallint")
                        .HasColumnName("int_versuch");

                    b.Property<int?>("IntWertungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    b.Property<float?>("RelLeistung")
                        .HasColumnType("real")
                        .HasColumnName("rel_leistung");

                    b.HasKey("IntJuryresultsid")
                        .HasName("pky_juryresultsid");

                    b.HasIndex("IntDisziplinenFelderid");

                    b.HasIndex("IntWertungenid");

                    b.ToTable("tfx_jury_results", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxKonten", b =>
                {
                    b.Property<int>("IntKontenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_kontenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntKontenid"));

                    b.Property<string>("VarBank")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_bank");

                    b.Property<string>("VarBlz")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("var_blz");

                    b.Property<string>("VarInhabe")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_inhabe");

                    b.Property<string>("VarKontonummer")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("var_kontonummer");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntKontenid")
                        .HasName("pky_kontenid");

                    b.ToTable("tfx_konten", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxLaender", b =>
                {
                    b.Property<int>("IntLaenderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_laenderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntLaenderid"));

                    b.Property<string>("VarKuerzel")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("var_kuerzel");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntLaenderid")
                        .HasName("pky_laenderid");

                    b.ToTable("tfx_laender", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxLayout", b =>
                {
                    b.Property<int>("IntLayoutid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_layoutid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntLayoutid"));

                    b.Property<string>("TxtComment")
                        .HasColumnType("text")
                        .HasColumnName("txt_comment");

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntLayoutid")
                        .HasName("pky_layoutid");

                    b.ToTable("tfx_layouts", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxLayoutFelder", b =>
                {
                    b.Property<int>("IntLayoutFelderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_layout_felderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntLayoutFelderid"));

                    b.Property<short?>("IntAlign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_align");

                    b.Property<short?>("IntLayer")
                        .HasColumnType("smallint")
                        .HasColumnName("int_layer");

                    b.Property<int>("IntLayoutid")
                        .HasColumnType("integer")
                        .HasColumnName("int_layoutid");

                    b.Property<short?>("IntTyp")
                        .HasColumnType("smallint")
                        .HasColumnName("int_typ");

                    b.Property<float?>("RelH")
                        .HasColumnType("real")
                        .HasColumnName("rel_h");

                    b.Property<float?>("RelW")
                        .HasColumnType("real")
                        .HasColumnName("rel_w");

                    b.Property<float?>("RelX")
                        .HasColumnType("real")
                        .HasColumnName("rel_x");

                    b.Property<float?>("RelY")
                        .HasColumnType("real")
                        .HasColumnName("rel_y");

                    b.Property<string>("VarFont")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_font");

                    b.Property<string>("VarValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_value");

                    b.HasKey("IntLayoutFelderid")
                        .HasName("pky_layout_felderid");

                    b.HasIndex("IntLayoutid");

                    b.ToTable("tfx_layout_felder", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxManXManAb", b =>
                {
                    b.Property<int>("IntManXManAbid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_man_x_man_abid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntManXManAbid"));

                    b.Property<int>("IntMannschaftenAbzugid")
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaften_abzugid");

                    b.Property<int>("IntMannschaftenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaftenid");

                    b.HasKey("IntManXManAbid")
                        .HasName("pky_man_x_man_abid");

                    b.HasIndex("IntMannschaftenAbzugid");

                    b.HasIndex("IntMannschaftenid");

                    b.ToTable("tfx_man_x_man_ab", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxManXTeilnehmer", b =>
                {
                    b.Property<int>("IntManXTeilnehmerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_man_x_teilnehmerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntManXTeilnehmerid"));

                    b.Property<int>("IntMannschaftenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaftenid");

                    b.Property<short?>("IntRunde")
                        .HasColumnType("smallint")
                        .HasColumnName("int_runde");

                    b.Property<int>("IntTeilnehmerid")
                        .HasColumnType("integer")
                        .HasColumnName("int_teilnehmerid");

                    b.HasKey("IntManXTeilnehmerid")
                        .HasName("pky_man_x_teilnehmerid");

                    b.HasIndex("IntMannschaftenid");

                    b.HasIndex("IntTeilnehmerid");

                    b.ToTable("tfx_man_x_teilnehmer", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxMannschaften", b =>
                {
                    b.Property<int>("IntMannschaftenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaftenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntMannschaftenid"));

                    b.Property<short?>("IntNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_nummer");

                    b.Property<int?>("IntStartnummer")
                        .HasColumnType("integer")
                        .HasColumnName("int_startnummer");

                    b.Property<int>("IntVereineid")
                        .HasColumnType("integer")
                        .HasColumnName("int_vereineid");

                    b.Property<int>("IntWettkaempfeid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfeid");

                    b.Property<string>("VarRiege")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_riege")
                        .HasDefaultValueSql("1");

                    b.HasKey("IntMannschaftenid")
                        .HasName("pky_mannschaftenid");

                    b.HasIndex("IntVereineid");

                    b.HasIndex("IntWettkaempfeid");

                    b.ToTable("tfx_mannschaften", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxMannschaftenAbzug", b =>
                {
                    b.Property<int>("IntMannschaftenAbzugid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaften_abzugid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntMannschaftenAbzugid"));

                    b.Property<float?>("RelAbzug")
                        .HasColumnType("real")
                        .HasColumnName("rel_abzug");

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntMannschaftenAbzugid")
                        .HasName("pky_mannschaften_abzugid");

                    b.ToTable("tfx_mannschaften_abzug", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxPersonen", b =>
                {
                    b.Property<int>("IntPersonenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_personenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntPersonenid"));

                    b.Property<string>("VarAdresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_adresse");

                    b.Property<string>("VarEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_email");

                    b.Property<string>("VarFax")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("var_fax");

                    b.Property<string>("VarNachname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_nachname");

                    b.Property<string>("VarOrt")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_ort");

                    b.Property<string>("VarPlz")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_plz");

                    b.Property<string>("VarTelefon")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("var_telefon");

                    b.Property<string>("VarVorname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_vorname");

                    b.HasKey("IntPersonenid")
                        .HasName("pky_personenid");

                    b.ToTable("tfx_personen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxQualiLeistungen", b =>
                {
                    b.Property<int>("IntQualiLeistungenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_quali_leistungenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntQualiLeistungenid"));

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<int>("IntWertungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    b.Property<float?>("RelLeistung")
                        .HasColumnType("real")
                        .HasColumnName("rel_leistung");

                    b.HasKey("IntQualiLeistungenid")
                        .HasName("pky_quali_leistungenid");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntWertungenid");

                    b.ToTable("tfx_quali_leistungen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxRiegenXDisziplinen", b =>
                {
                    b.Property<int>("IntRiegenXDisziplinenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_riegen_x_disziplinenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntRiegenXDisziplinenid"));

                    b.Property<bool?>("BolErstesGeraet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_erstes_geraet");

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntRunde")
                        .HasColumnType("smallint")
                        .HasColumnName("int_runde");

                    b.Property<int>("IntStatusid")
                        .HasColumnType("integer")
                        .HasColumnName("int_statusid");

                    b.Property<int>("IntVeranstaltungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_veranstaltungenid");

                    b.Property<string>("VarRiege")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_riege");

                    b.HasKey("IntRiegenXDisziplinenid")
                        .HasName("pky_riegen_x_disziplinenid");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntStatusid");

                    b.HasIndex("IntVeranstaltungenid");

                    b.ToTable("tfx_riegen_x_disziplinen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxSport", b =>
                {
                    b.Property<int>("IntSportid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_sportid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntSportid"));

                    b.Property<string>("VarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_name");

                    b.HasKey("IntSportid")
                        .HasName("pky_sportid");

                    b.ToTable("tfx_sport", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxStartreihenfolge", b =>
                {
                    b.Property<int>("IntStartreihenfolgeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_startreihenfolgeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntStartreihenfolgeid"));

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_kp");

                    b.Property<short?>("IntPos")
                        .HasColumnType("smallint")
                        .HasColumnName("int_pos");

                    b.Property<int>("IntWertungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    b.HasKey("IntStartreihenfolgeid")
                        .HasName("pky_startreihenfolge");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntWertungenid");

                    b.ToTable("tfx_startreihenfolge", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.Status", b =>
                {
                    b.Property<int>("IntStatusid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_statusid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntStatusid"));

                    b.Property<string>("AryColorcode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ary_colorcode")
                        .HasDefaultValueSql("'{0,0,0}'::character varying");

                    b.Property<bool?>("BolBogen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_bogen");

                    b.Property<bool?>("BolKarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bol_karte");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntStatusid")
                        .HasName("pky_statusid");

                    b.ToTable("tfx_status", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.Athlete", b =>
                {
                    b.Property<int>("IntTeilnehmerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_teilnehmerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntTeilnehmerid"));

                    b.Property<bool?>("BoolNurJahr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("bool_nur_jahr");

                    b.Property<DateOnly?>("DatGeburtstag")
                        .HasColumnType("date")
                        .HasColumnName("dat_geburtstag");

                    b.Property<short>("IntGeschlecht")
                        .HasColumnType("smallint")
                        .HasColumnName("int_geschlecht");

                    b.Property<int?>("IntStartpassnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("int_startpassnummer");

                    b.Property<int>("IntVereineid")
                        .HasColumnType("integer")
                        .HasColumnName("int_vereineid");

                    b.Property<string>("VarNachname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_nachname");

                    b.Property<string>("VarVorname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_vorname");

                    b.HasKey("IntTeilnehmerid")
                        .HasName("pky_teilnehmerid");

                    b.HasIndex("IntVereineid");

                    b.ToTable("tfx_teilnehmer", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.Event", b =>
                {
                    b.Property<int>("IntVeranstaltungenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_veranstaltungenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntVeranstaltungenid"));

                    b.Property<bool?>("BolFaelligNichtantritt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_faellig_nichtantritt");

                    b.Property<bool?>("BolNachmeldungMoeglich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_nachmeldung_moeglich");

                    b.Property<bool?>("BolRundenwettkampf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_rundenwettkampf");

                    b.Property<bool?>("BolUmmeldungMoeglich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_ummeldung_moeglich");

                    b.Property<DateOnly>("DatBis")
                        .HasColumnType("date")
                        .HasColumnName("dat_bis");

                    b.Property<DateOnly?>("DatMeldeschluss")
                        .HasColumnType("date")
                        .HasColumnName("dat_meldeschluss");

                    b.Property<DateOnly>("DatVon")
                        .HasColumnType("date")
                        .HasColumnName("dat_von");

                    b.Property<int?>("IntAnsprechpartner")
                        .HasColumnType("integer")
                        .HasColumnName("int_ansprechpartner");

                    b.Property<short?>("IntEdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_edv");

                    b.Property<int?>("IntHauptwettkampf")
                        .HasColumnType("integer")
                        .HasColumnName("int_hauptwettkampf");

                    b.Property<short?>("IntHelfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_helfer");

                    b.Property<short?>("IntKampfrichter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_kampfrichter");

                    b.Property<int?>("IntKontenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_kontenid");

                    b.Property<int?>("IntMeldungAn")
                        .HasColumnType("integer")
                        .HasColumnName("int_meldung_an");

                    b.Property<short?>("IntRunde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_runde");

                    b.Property<int>("IntWettkampforteid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkampforteid");

                    b.Property<float?>("RelMeldegeld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("rel_meldegeld")
                        .HasDefaultValueSql("0");

                    b.Property<float?>("RelNachmeldung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("rel_nachmeldung")
                        .HasDefaultValueSql("0");

                    b.Property<string>("TxtHinweise")
                        .HasColumnType("text")
                        .HasColumnName("txt_hinweise");

                    b.Property<string>("TxtKampfrichter")
                        .HasColumnType("text")
                        .HasColumnName("txt_kampfrichter");

                    b.Property<string>("TxtMeldungAn")
                        .HasColumnType("text")
                        .HasColumnName("txt_meldung_an");

                    b.Property<string>("TxtSiegerauszeichnung")
                        .HasColumnType("text")
                        .HasColumnName("txt_siegerauszeichnung");

                    b.Property<string>("TxtStartberechtigung")
                        .HasColumnType("text")
                        .HasColumnName("txt_startberechtigung");

                    b.Property<string>("TxtTeilnahmebedingungen")
                        .HasColumnType("text")
                        .HasColumnName("txt_teilnahmebedingungen");

                    b.Property<string>("VarMeldungWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_meldung_website");

                    b.Property<string>("VarName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("var_name");

                    b.Property<string>("VarVeranstalter")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_veranstalter");

                    b.Property<string>("VarVerwendungszweck")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_verwendungszweck");

                    b.HasKey("IntVeranstaltungenid")
                        .HasName("pky_veranstaltungenid");

                    b.HasIndex("IntAnsprechpartner");

                    b.HasIndex("IntHauptwettkampf");

                    b.HasIndex("IntKontenid");

                    b.HasIndex("IntMeldungAn");

                    b.HasIndex("IntWettkampforteid");

                    b.ToTable("tfx_veranstaltungen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxVerbaende", b =>
                {
                    b.Property<int>("IntVerbaendeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_verbaendeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntVerbaendeid"));

                    b.Property<int>("IntLaenderid")
                        .HasColumnType("integer")
                        .HasColumnName("int_laenderid");

                    b.Property<string>("VarKuerzel")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("var_kuerzel");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.HasKey("IntVerbaendeid")
                        .HasName("pky_verbaendeid");

                    b.HasIndex("IntLaenderid");

                    b.ToTable("tfx_verbaende", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxVereine", b =>
                {
                    b.Property<int>("IntVereineid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_vereineid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntVereineid"));

                    b.Property<int>("IntGaueid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("int_gaueid");

                    b.Property<int?>("IntPersonenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_personenid");

                    b.Property<short?>("IntStartOrt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_start_ort");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.Property<string>("VarWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_website");

                    b.HasKey("IntVereineid")
                        .HasName("pky_vereineid");

                    b.HasIndex("IntGaueid");

                    b.HasIndex("IntPersonenid");

                    b.ToTable("tfx_vereine", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungen", b =>
                {
                    b.Property<int>("IntWertungenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWertungenid"));

                    b.Property<bool?>("BolAk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_ak");

                    b.Property<bool?>("BolStartetNicht")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_startet_nicht");

                    b.Property<int?>("IntGruppenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_gruppenid");

                    b.Property<int?>("IntMannschaftenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_mannschaftenid");

                    b.Property<short?>("IntRunde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_runde");

                    b.Property<int?>("IntStartnummer")
                        .HasColumnType("integer")
                        .HasColumnName("int_startnummer");

                    b.Property<int>("IntStatusid")
                        .HasColumnType("integer")
                        .HasColumnName("int_statusid");

                    b.Property<int?>("IntTeilnehmerid")
                        .HasColumnType("integer")
                        .HasColumnName("int_teilnehmerid");

                    b.Property<int>("IntWettkaempfeid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfeid");

                    b.Property<string>("VarComment")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_comment");

                    b.Property<string>("VarRiege")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("var_riege");

                    b.HasKey("IntWertungenid")
                        .HasName("pky_wertungenid");

                    b.HasIndex("IntGruppenid");

                    b.HasIndex("IntMannschaftenid");

                    b.HasIndex("IntStatusid");

                    b.HasIndex("IntTeilnehmerid");

                    b.HasIndex("IntWettkaempfeid");

                    b.ToTable("tfx_wertungen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungenDetail", b =>
                {
                    b.Property<int>("IntWertungenDetailsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungen_detailsid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWertungenDetailsid"));

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_kp");

                    b.Property<short?>("IntVersuch")
                        .HasColumnType("smallint")
                        .HasColumnName("int_versuch");

                    b.Property<int>("IntWertungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    b.Property<float?>("RelLeistung")
                        .HasColumnType("real")
                        .HasColumnName("rel_leistung");

                    b.HasKey("IntWertungenDetailsid")
                        .HasName("pky_wertungen_detailsid");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntWertungenid");

                    b.ToTable("tfx_wertungen_details", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungenXDisziplinen", b =>
                {
                    b.Property<int>("IntWertungenXDisziplinenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungen_x_disziplinenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWertungenXDisziplinenid"));

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<int>("IntWertungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wertungenid");

                    b.HasKey("IntWertungenXDisziplinenid")
                        .HasName("pky_wertungen_x_disziplinenid");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntWertungenid");

                    b.ToTable("tfx_wertungen_x_disziplinen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfe", b =>
                {
                    b.Property<int>("IntWettkaempfeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWettkaempfeid"));

                    b.Property<bool?>("BolAkAnzeigen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_ak_anzeigen");

                    b.Property<bool?>("BolGerpkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_gerpkt");

                    b.Property<bool?>("BolInfoAnzeigen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_info_anzeigen");

                    b.Property<bool?>("BolKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_kp");

                    b.Property<bool?>("BolMansort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_mansort");

                    b.Property<bool?>("BolSortasc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_sortasc");

                    b.Property<bool?>("BolStreichwertung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_streichwertung");

                    b.Property<bool?>("BolWahlwettkampf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_wahlwettkampf");

                    b.Property<short?>("IntAnzStreich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_anz_streich");

                    b.Property<short?>("IntBahn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_bahn");

                    b.Property<int>("IntBereicheid")
                        .HasColumnType("integer")
                        .HasColumnName("int_bereicheid");

                    b.Property<short?>("IntDurchgang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("int_durchgang");

                    b.Property<short?>("IntQualifikation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_qualifikation");

                    b.Property<short?>("IntTyp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_typ");

                    b.Property<int>("IntVeranstaltungenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_veranstaltungenid");

                    b.Property<short?>("IntWertungen")
                        .HasColumnType("smallint")
                        .HasColumnName("int_wertungen");

                    b.Property<TimeOnly?>("TimEinturnen")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tim_einturnen");

                    b.Property<TimeOnly?>("TimStartzeit")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tim_startzeit");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.Property<string>("VarNummer")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_nummer");

                    b.Property<short?>("YerBis")
                        .HasColumnType("smallint")
                        .HasColumnName("yer_bis");

                    b.Property<short>("YerVon")
                        .HasColumnType("smallint")
                        .HasColumnName("yer_von");

                    b.HasKey("IntWettkaempfeid")
                        .HasName("pky_wettkaempfeid");

                    b.HasIndex("IntBereicheid");

                    b.HasIndex("IntVeranstaltungenid");

                    b.ToTable("tfx_wettkaempfe", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfeDispo", b =>
                {
                    b.Property<int>("IntWettkaempfeDisposid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfe_disposid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWettkaempfeDisposid"));

                    b.Property<short?>("IntKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_kp");

                    b.Property<short?>("IntSortx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_sortx");

                    b.Property<short?>("IntSorty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("int_sorty");

                    b.Property<int>("IntWettkaempfeXDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfe_x_disziplinenid");

                    b.HasKey("IntWettkaempfeDisposid")
                        .HasName("pky_wettkaempfe_disposid");

                    b.HasIndex("IntWettkaempfeXDisziplinenid");

                    b.ToTable("tfx_wettkaempfe_dispos", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfeXDisziplinen", b =>
                {
                    b.Property<int>("IntWettkaempfeXDisziplinenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfe_x_disziplinenid")
                        .HasDefaultValueSql("nextval('tfx_wettkaempfe_x_disziplinen_int_wettkaempfe_x_disziplinen_seq'::regclass)");

                    b.Property<bool?>("BolKp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bol_kp");

                    b.Property<int>("IntDisziplinenid")
                        .HasColumnType("integer")
                        .HasColumnName("int_disziplinenid");

                    b.Property<short?>("IntSortierung")
                        .HasColumnType("smallint")
                        .HasColumnName("int_sortierung");

                    b.Property<int>("IntWettkaempfeid")
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkaempfeid");

                    b.Property<float?>("RelMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("rel_max")
                        .HasDefaultValueSql("0");

                    b.Property<string>("VarAusschreibung")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("var_ausschreibung");

                    b.HasKey("IntWettkaempfeXDisziplinenid")
                        .HasName("pky_wettkaempfe_x_disziplinenid");

                    b.HasIndex("IntDisziplinenid");

                    b.HasIndex("IntWettkaempfeid");

                    b.ToTable("tfx_wettkaempfe_x_disziplinen", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkampforte", b =>
                {
                    b.Property<int>("IntWettkampforteid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("int_wettkampforteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntWettkampforteid"));

                    b.Property<string>("VarAdresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("var_adresse");

                    b.Property<string>("VarName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_name");

                    b.Property<string>("VarOrt")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("var_ort");

                    b.Property<string>("VarPlz")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("var_plz");

                    b.HasKey("IntWettkampforteid")
                        .HasName("pky_wettkampforteid");

                    b.ToTable("tfx_wettkampforte", (string)null);
                });

            modelBuilder.Entity("turnfix.Models.TfxDisgrpXDisziplinen", b =>
                {
                    b.HasOne("turnfix.Models.TfxDisziplinenGruppen", "IntDisziplinenGruppen")
                        .WithMany("TfxDisgrpXDisziplinens")
                        .HasForeignKey("IntDisziplinenGruppenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinen_gruppenid");

                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxDisgrpXDisziplinens")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinen");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntDisziplinenGruppen");
                });

            modelBuilder.Entity("turnfix.Models.Discipline", b =>
                {
                    b.HasOne("turnfix.Models.TfxFormeln", "IntFormel")
                        .WithMany("TfxDisziplinens")
                        .HasForeignKey("IntFormelid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_formelid");

                    b.HasOne("turnfix.Models.TfxSport", "IntSport")
                        .WithMany("TfxDisziplinens")
                        .HasForeignKey("IntSportid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_sportid");

                    b.Navigation("IntFormel");

                    b.Navigation("IntSport");
                });

            modelBuilder.Entity("turnfix.Models.TfxDisziplinenFelder", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxDisziplinenFelders")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.Navigation("IntDisziplinen");
                });

            modelBuilder.Entity("turnfix.Models.TfxGaue", b =>
                {
                    b.HasOne("turnfix.Models.TfxVerbaende", "IntVerbaende")
                        .WithMany("TfxGaues")
                        .HasForeignKey("IntVerbaendeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_verbaendeid");

                    b.Navigation("IntVerbaende");
                });

            modelBuilder.Entity("turnfix.Models.TfxGruppenXTeilnehmer", b =>
                {
                    b.HasOne("turnfix.Models.TfxGruppen", "IntGruppen")
                        .WithMany("TfxGruppenXTeilnehmers")
                        .HasForeignKey("IntGruppenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_gruppenid");

                    b.HasOne("turnfix.Models.Athlete", "IntTeilnehmer")
                        .WithMany("TfxGruppenXTeilnehmers")
                        .HasForeignKey("IntTeilnehmerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_teilnehmerid");

                    b.Navigation("IntGruppen");

                    b.Navigation("IntTeilnehmer");
                });

            modelBuilder.Entity("turnfix.Models.TfxJuryResult", b =>
                {
                    b.HasOne("turnfix.Models.TfxDisziplinenFelder", "IntDisziplinenFelder")
                        .WithMany("TfxJuryResults")
                        .HasForeignKey("IntDisziplinenFelderid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_disziplinen_felderid");

                    b.HasOne("turnfix.Models.TfxWertungen", "IntWertungen")
                        .WithMany("TfxJuryResults")
                        .HasForeignKey("IntWertungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fky_wertungenid");

                    b.Navigation("IntDisziplinenFelder");

                    b.Navigation("IntWertungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxLayoutFelder", b =>
                {
                    b.HasOne("turnfix.Models.TfxLayout", "IntLayout")
                        .WithMany("TfxLayoutFelders")
                        .HasForeignKey("IntLayoutid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_layoutid");

                    b.Navigation("IntLayout");
                });

            modelBuilder.Entity("turnfix.Models.TfxManXManAb", b =>
                {
                    b.HasOne("turnfix.Models.TfxMannschaftenAbzug", "IntMannschaftenAbzug")
                        .WithMany("TfxManXManAbs")
                        .HasForeignKey("IntMannschaftenAbzugid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_mannschaften_abzugid");

                    b.HasOne("turnfix.Models.TfxMannschaften", "IntMannschaften")
                        .WithMany("TfxManXManAbs")
                        .HasForeignKey("IntMannschaftenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_mannschaftenid");

                    b.Navigation("IntMannschaften");

                    b.Navigation("IntMannschaftenAbzug");
                });

            modelBuilder.Entity("turnfix.Models.TfxManXTeilnehmer", b =>
                {
                    b.HasOne("turnfix.Models.TfxMannschaften", "IntMannschaften")
                        .WithMany("TfxManXTeilnehmers")
                        .HasForeignKey("IntMannschaftenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_mannschaftenid");

                    b.HasOne("turnfix.Models.Athlete", "IntTeilnehmer")
                        .WithMany("TfxManXTeilnehmers")
                        .HasForeignKey("IntTeilnehmerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_teilnehmerid");

                    b.Navigation("IntMannschaften");

                    b.Navigation("IntTeilnehmer");
                });

            modelBuilder.Entity("turnfix.Models.TfxMannschaften", b =>
                {
                    b.HasOne("turnfix.Models.TfxVereine", "IntVereine")
                        .WithMany("TfxMannschaftens")
                        .HasForeignKey("IntVereineid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_vereineid");

                    b.HasOne("turnfix.Models.TfxWettkaempfe", "IntWettkaempfe")
                        .WithMany("TfxMannschaftens")
                        .HasForeignKey("IntWettkaempfeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wettkaempfeid");

                    b.Navigation("IntVereine");

                    b.Navigation("IntWettkaempfe");
                });

            modelBuilder.Entity("turnfix.Models.TfxQualiLeistungen", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxQualiLeistungens")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.HasOne("turnfix.Models.TfxWertungen", "IntWertungen")
                        .WithMany("TfxQualiLeistungens")
                        .HasForeignKey("IntWertungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("int_wertungenid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntWertungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxRiegenXDisziplinen", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxRiegenXDisziplinens")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.HasOne("turnfix.Models.Status", "IntStatus")
                        .WithMany("TfxRiegenXDisziplinens")
                        .HasForeignKey("IntStatusid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_statusid");

                    b.HasOne("turnfix.Models.Event", "IntVeranstaltungen")
                        .WithMany("TfxRiegenXDisziplinens")
                        .HasForeignKey("IntVeranstaltungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_veranstaltungenid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntStatus");

                    b.Navigation("IntVeranstaltungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxStartreihenfolge", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxStartreihenfolges")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinen");

                    b.HasOne("turnfix.Models.TfxWertungen", "IntWertungen")
                        .WithMany("TfxStartreihenfolges")
                        .HasForeignKey("IntWertungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wertungenid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntWertungen");
                });

            modelBuilder.Entity("turnfix.Models.Athlete", b =>
                {
                    b.HasOne("turnfix.Models.TfxVereine", "IntVereine")
                        .WithMany("TfxTeilnehmers")
                        .HasForeignKey("IntVereineid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_vereineid");

                    b.Navigation("IntVereine");
                });

            modelBuilder.Entity("turnfix.Models.Event", b =>
                {
                    b.HasOne("turnfix.Models.TfxPersonen", "IntAnsprechpartnerNavigation")
                        .WithMany("TfxVeranstaltungenIntAnsprechpartnerNavigations")
                        .HasForeignKey("IntAnsprechpartner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_ansprechpartner");

                    b.HasOne("turnfix.Models.Event", "IntHauptwettkampfNavigation")
                        .WithMany("InverseIntHauptwettkampfNavigation")
                        .HasForeignKey("IntHauptwettkampf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_hauptwettkampf");

                    b.HasOne("turnfix.Models.TfxKonten", "IntKonten")
                        .WithMany("TfxVeranstaltungens")
                        .HasForeignKey("IntKontenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_kontenid");

                    b.HasOne("turnfix.Models.TfxPersonen", "IntMeldungAnNavigation")
                        .WithMany("TfxVeranstaltungenIntMeldungAnNavigations")
                        .HasForeignKey("IntMeldungAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_meldung_an");

                    b.HasOne("turnfix.Models.TfxWettkampforte", "IntWettkampforte")
                        .WithMany("TfxVeranstaltungens")
                        .HasForeignKey("IntWettkampforteid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_wettkampforteid");

                    b.Navigation("IntAnsprechpartnerNavigation");

                    b.Navigation("IntHauptwettkampfNavigation");

                    b.Navigation("IntKonten");

                    b.Navigation("IntMeldungAnNavigation");

                    b.Navigation("IntWettkampforte");
                });

            modelBuilder.Entity("turnfix.Models.TfxVerbaende", b =>
                {
                    b.HasOne("turnfix.Models.TfxLaender", "IntLaender")
                        .WithMany("TfxVerbaendes")
                        .HasForeignKey("IntLaenderid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkx_laenderid");

                    b.Navigation("IntLaender");
                });

            modelBuilder.Entity("turnfix.Models.TfxVereine", b =>
                {
                    b.HasOne("turnfix.Models.TfxGaue", "IntGaue")
                        .WithMany("TfxVereines")
                        .HasForeignKey("IntGaueid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_gaueid");

                    b.HasOne("turnfix.Models.TfxPersonen", "IntPersonen")
                        .WithMany("TfxVereines")
                        .HasForeignKey("IntPersonenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_personenid");

                    b.Navigation("IntGaue");

                    b.Navigation("IntPersonen");
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungen", b =>
                {
                    b.HasOne("turnfix.Models.TfxGruppen", "IntGruppen")
                        .WithMany("TfxWertungens")
                        .HasForeignKey("IntGruppenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fky_gruppenid");

                    b.HasOne("turnfix.Models.TfxMannschaften", "IntMannschaften")
                        .WithMany("TfxWertungens")
                        .HasForeignKey("IntMannschaftenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fky_mannschaftenid");

                    b.HasOne("turnfix.Models.Status", "IntStatus")
                        .WithMany("TfxWertungens")
                        .HasForeignKey("IntStatusid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_statusid");

                    b.HasOne("turnfix.Models.Athlete", "IntTeilnehmer")
                        .WithMany("TfxWertungens")
                        .HasForeignKey("IntTeilnehmerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fky_teilnehmerid");

                    b.HasOne("turnfix.Models.TfxWettkaempfe", "IntWettkaempfe")
                        .WithMany("TfxWertungens")
                        .HasForeignKey("IntWettkaempfeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wettkaempfeid");

                    b.Navigation("IntGruppen");

                    b.Navigation("IntMannschaften");

                    b.Navigation("IntStatus");

                    b.Navigation("IntTeilnehmer");

                    b.Navigation("IntWettkaempfe");
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungenDetail", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxWertungenDetails")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.HasOne("turnfix.Models.TfxWertungen", "IntWertungen")
                        .WithMany("TfxWertungenDetails")
                        .HasForeignKey("IntWertungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wertungenid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntWertungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungenXDisziplinen", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxWertungenXDisziplinens")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.HasOne("turnfix.Models.TfxWertungen", "IntWertungen")
                        .WithMany("TfxWertungenXDisziplinens")
                        .HasForeignKey("IntWertungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wertungenid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntWertungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfe", b =>
                {
                    b.HasOne("turnfix.Models.TfxBereiche", "IntBereiche")
                        .WithMany("TfxWettkaempves")
                        .HasForeignKey("IntBereicheid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_bereicheid");

                    b.HasOne("turnfix.Models.Event", "IntVeranstaltungen")
                        .WithMany("TfxWettkaempves")
                        .HasForeignKey("IntVeranstaltungenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_veranstaltungenid");

                    b.Navigation("IntBereiche");

                    b.Navigation("IntVeranstaltungen");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfeDispo", b =>
                {
                    b.HasOne("turnfix.Models.TfxWettkaempfeXDisziplinen", "IntWettkaempfeXDisziplinen")
                        .WithMany("TfxWettkaempfeDispos")
                        .HasForeignKey("IntWettkaempfeXDisziplinenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wettkaempfe_x_disziplinenid");

                    b.Navigation("IntWettkaempfeXDisziplinen");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfeXDisziplinen", b =>
                {
                    b.HasOne("turnfix.Models.Discipline", "IntDisziplinen")
                        .WithMany("TfxWettkaempfeXDisziplinens")
                        .HasForeignKey("IntDisziplinenid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fky_disziplinenid");

                    b.HasOne("turnfix.Models.TfxWettkaempfe", "IntWettkaempfe")
                        .WithMany("TfxWettkaempfeXDisziplinens")
                        .HasForeignKey("IntWettkaempfeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fky_wettkaempfeid");

                    b.Navigation("IntDisziplinen");

                    b.Navigation("IntWettkaempfe");
                });

            modelBuilder.Entity("turnfix.Models.TfxBereiche", b =>
                {
                    b.Navigation("TfxWettkaempves");
                });

            modelBuilder.Entity("turnfix.Models.Discipline", b =>
                {
                    b.Navigation("TfxDisgrpXDisziplinens");

                    b.Navigation("TfxDisziplinenFelders");

                    b.Navigation("TfxQualiLeistungens");

                    b.Navigation("TfxRiegenXDisziplinens");

                    b.Navigation("TfxStartreihenfolges");

                    b.Navigation("TfxWertungenDetails");

                    b.Navigation("TfxWertungenXDisziplinens");

                    b.Navigation("TfxWettkaempfeXDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.TfxDisziplinenFelder", b =>
                {
                    b.Navigation("TfxJuryResults");
                });

            modelBuilder.Entity("turnfix.Models.TfxDisziplinenGruppen", b =>
                {
                    b.Navigation("TfxDisgrpXDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.TfxFormeln", b =>
                {
                    b.Navigation("TfxDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.TfxGaue", b =>
                {
                    b.Navigation("TfxVereines");
                });

            modelBuilder.Entity("turnfix.Models.TfxGruppen", b =>
                {
                    b.Navigation("TfxGruppenXTeilnehmers");

                    b.Navigation("TfxWertungens");
                });

            modelBuilder.Entity("turnfix.Models.TfxKonten", b =>
                {
                    b.Navigation("TfxVeranstaltungens");
                });

            modelBuilder.Entity("turnfix.Models.TfxLaender", b =>
                {
                    b.Navigation("TfxVerbaendes");
                });

            modelBuilder.Entity("turnfix.Models.TfxLayout", b =>
                {
                    b.Navigation("TfxLayoutFelders");
                });

            modelBuilder.Entity("turnfix.Models.TfxMannschaften", b =>
                {
                    b.Navigation("TfxManXManAbs");

                    b.Navigation("TfxManXTeilnehmers");

                    b.Navigation("TfxWertungens");
                });

            modelBuilder.Entity("turnfix.Models.TfxMannschaftenAbzug", b =>
                {
                    b.Navigation("TfxManXManAbs");
                });

            modelBuilder.Entity("turnfix.Models.TfxPersonen", b =>
                {
                    b.Navigation("TfxVeranstaltungenIntAnsprechpartnerNavigations");

                    b.Navigation("TfxVeranstaltungenIntMeldungAnNavigations");

                    b.Navigation("TfxVereines");
                });

            modelBuilder.Entity("turnfix.Models.TfxSport", b =>
                {
                    b.Navigation("TfxDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.Status", b =>
                {
                    b.Navigation("TfxRiegenXDisziplinens");

                    b.Navigation("TfxWertungens");
                });

            modelBuilder.Entity("turnfix.Models.Athlete", b =>
                {
                    b.Navigation("TfxGruppenXTeilnehmers");

                    b.Navigation("TfxManXTeilnehmers");

                    b.Navigation("TfxWertungens");
                });

            modelBuilder.Entity("turnfix.Models.Event", b =>
                {
                    b.Navigation("InverseIntHauptwettkampfNavigation");

                    b.Navigation("TfxRiegenXDisziplinens");

                    b.Navigation("TfxWettkaempves");
                });

            modelBuilder.Entity("turnfix.Models.TfxVerbaende", b =>
                {
                    b.Navigation("TfxGaues");
                });

            modelBuilder.Entity("turnfix.Models.TfxVereine", b =>
                {
                    b.Navigation("TfxMannschaftens");

                    b.Navigation("TfxTeilnehmers");
                });

            modelBuilder.Entity("turnfix.Models.TfxWertungen", b =>
                {
                    b.Navigation("TfxJuryResults");

                    b.Navigation("TfxQualiLeistungens");

                    b.Navigation("TfxStartreihenfolges");

                    b.Navigation("TfxWertungenDetails");

                    b.Navigation("TfxWertungenXDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfe", b =>
                {
                    b.Navigation("TfxMannschaftens");

                    b.Navigation("TfxWertungens");

                    b.Navigation("TfxWettkaempfeXDisziplinens");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkaempfeXDisziplinen", b =>
                {
                    b.Navigation("TfxWettkaempfeDispos");
                });

            modelBuilder.Entity("turnfix.Models.TfxWettkampforte", b =>
                {
                    b.Navigation("TfxVeranstaltungens");
                });
#pragma warning restore 612, 618
        }
    }
}
